Restapi endpoint support
collective/collective.taxonomy pull request #126
Opened 2022-03-14 10:00 UTC by nileshgulia1

The endpoint was originally extracted from https://github.com/eea/eea.api.taxonomy. Continuing the work done by @cekk. 
The idea is to utilise this endpoint in volto-addon controlpanel https://github.com/eea/volto-taxonomy/tree/develop

2023-05-25 12:00 UTC, MrTango approved these changes
with the small cleanup comments, it looks good to me

2023-05-25 12:07 UTC, petschki requested changes
would be nice if the README would be updated too.

2023-05-25 12:07 UTC, petschki commented on .installed.txt
no

2023-05-26 07:36 UTC, nileshgulia1 commented on .DS_Store
Removed in [b6da62a](https://github.com/collective/collective.taxonomy/pull/126/commits/b6da62a4a77c6dfe46ff56b40c85ef484a38225e)

2023-05-26 07:58 UTC, MrTango commented
@nileshgulia1 thx

2023-05-26 07:58 UTC, merged