fix keyword comparison
collective/collective.taxonomy pull request #161
Opened 2024-07-19 15:32 UTC by mamico

Fix a bug that occurred when two taxonomy keywords at the same level started the same way.

2024-07-19 17:08 UTC, petschki requested changes

2024-07-19 17:08 UTC, petschki commented on src/collective/taxonomy/indexer.py
> +                value_split = value.split("\u241f")
I recommend to use the global var instead of the value `"\u241F"`:

```
from collective.taxonomy import PATH_SEPARATOR
```

2024-07-19 17:10 UTC, petschki commented
Note: the breaking circular dependency check is unrelated to this PR. We should disable it here until the core packages are clean.

2024-07-19 18:28 UTC, petschki approved these changes

2024-07-19 18:28 UTC, merged

2024-07-21 11:19 UTC, mamico commented
Thanks @petschki. Could you do a new release on pypi?

2024-07-21 12:22 UTC, petschki commented
done https://pypi.org/project/collective.taxonomy/