Config with default template 5d22fbf8
collective/collective.taxonomy pull request #166
Opened 2024-10-16 12:00 UTC by 1letter

- fix for #165
- add a robot test
- update config with plone/meta

2024-10-16 18:54 UTC, 1letter commented
@petschki short explanation for the changes by me. the command `tox -e lint` format the attribute `multiple=""` to `multiple`, that is from point of HTML standard view okay. but then it will be rendered in the template to `multiplemultiple` and a multiselect don't work. I decide me to remove the attribute in the template, the lint process don't touch the attribute and the bug is gone. what do you think? Is this solution okay?

2024-10-16 21:48 UTC, petschki requested changes

2024-10-16 21:48 UTC, petschki commented on src/collective/taxonomy/widget_input.pt
Two questions:

1. what about the second "multiple" in the `to` field?
2. if multiple is missing, are there problems when saving multiple values?

2024-10-17 05:48 UTC, petschki commented on src/collective/taxonomy/widget_input.pt
OK I see now that the `multiple` is set in `tal:attributes` so its OK to remove it from the markup.

But TBH it smells a bit like a bug in Chameleon template rendering engine, because if I do `multiple=""` in the widget markup it gets replaced correctly with `multiple="multiple"` (thats what `z3c.form OrderedSelect` widget defines here: https://github.com/zopefoundation/z3c.form/blob/master/src/z3c/form/browser/orderedselect.py#L36) -> but according to the specs, those "boolean html attributes" should be handled correctly if they are present without a value (https://developer.mozilla.org/en-US/docs/Glossary/Boolean/HTML)

So if you remove the second multiple in the `to` field too, this is approved.

2024-10-17 06:30 UTC, petschki commented on src/collective/taxonomy/widget_input.pt
related 😉 

https://github.com/collective/zpretty/issues/123

2024-10-17 06:41 UTC, 1letter commented on src/collective/taxonomy/widget_input.pt
> related 😉
> 
> [collective/zpretty#123](https://github.com/collective/zpretty/issues/123)

Okay, a new task for the week ;-)

2024-10-17 06:46 UTC, petschki commented on src/collective/taxonomy/widget_input.pt
Root cause: https://github.com/malthe/chameleon/issues/429

2024-10-17 06:58 UTC, merged